import {scenes,illustration,palette,colorNames,ensureArt,levels} from './scenes.js?v=3.4';
const $=s=>document.querySelector(s),KEY='ll-coloring-bible-release-v3',LEGACY_KEY='ll-coloring-bible-release-v2';let saved={works:{},finished:[]};try{const x=JSON.parse(localStorage.getItem(KEY)||localStorage.getItem(LEGACY_KEY)||localStorage.getItem('ll-coloring-bible-release-v1'));if(x&&x.works&&Array.isArray(x.finished))saved=x;}catch{}
let view='journey',current=null,difficulty='easy',mode='guided',selected=0,custom=palette[0],numbers=true,regions=[],fills={},history=[],future=[],pan=false,zoom=1,tx=0,ty=0,toastTimer,completionShown=false,eraser=false,tray=false,loadingToken=0,artReady=false;
const tabs=[['journey','Bible Journey'],['old','Old Testament'],['jesus','Life of Jesus'],['church','Early Church'],['free','Free Color'],['artwork','My Artwork / Progress']];
function message(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2700);}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(saved));return true;}catch{message('Storage unavailable. Download your picture before leaving.');return false;}}
function key(){return `${current.id}:${difficulty}:${mode}:art3`;}
function saveWork(){if(!current||!artReady)return;saved.works[key()]={fills:{...fills},updated:Date.now(),total:regions.length,artVersion:difficulty.startsWith('v2-')?2:1};saved.lastScene={id:current.id,difficulty,mode};persist();}
function percent(data,total){return Math.round(Object.keys(data).length/total*100)||0;}
function progress(scene){let best=0;for(const [k,w] of Object.entries(saved.works)){if(k.startsWith(scene.id+':')){const d=k.split(':')[1];const total=w.total||illustration(scene,d).regions.length;if(total)best=Math.max(best,Math.min(100,percent(w.fills,total)));}}return best;}
function showModal(html){const d=$('#modal');d.innerHTML=html;d.showModal();}
function closeModal(){$('#modal').close();}
function navigation(){ $('#navigation').innerHTML=tabs.map(([id,title])=>`<button data-tab="${id}" class="${view===id?'active':''}" aria-current="${view===id?'page':'false'}">${title}</button>`).join('');}
function nextScene(){return scenes.find(s=>!saved.finished.includes(s.id))||scenes[0];}
function decorative(svg){return svg.replace(/ role="button" tabindex="0"/g,'').replace('class="color-art"','class="color-art" aria-hidden="true"');}
function renderGallery(){++loadingToken;artReady=false;current=null;delete saved.lastScene;persist();document.body.classList.remove('coloring');navigation();const next=nextScene(),completed=saved.finished.length;let list=scenes;
 if(view==='old')list=scenes.filter(s=>s.group==='Old Testament');if(view==='jesus')list=scenes.filter(s=>s.group==='Life of Jesus');if(view==='church')list=scenes.filter(s=>s.group==='Early Church');if(view==='artwork')list=scenes.filter(s=>Object.entries(saved.works).some(([k,w])=>k.startsWith(s.id+':')&&Object.keys(w.fills).length>0));
 const titles={journey:'One story. So many colors.',old:'The Old Testament',jesus:'The life of Jesus',church:'Faith, shared with the world',free:'Your colors. Your imagination.',artwork:'Your little gallery'};
 const hero=view==='journey'?`<section class="hero"><div><span class="eyebrow">GENESIS TO REVELATION · VOLUME ONE</span><h1>A little color.<br>A beautiful story.</h1><p>Slow down, discover Scripture, and bring each page to life. A peaceful coloring journey for every age.</p><div class="hero-actions"><button class="primary" data-open="${next.id}">${completed?'Continue your journey':'Begin in Genesis'} →</button><button class="quiet" data-open="david">Try the V2 showcase</button><button class="quiet" data-tab="free">Try free color</button></div><div class="journey-status">${completed} of ${scenes.length} stories completed</div><div class="bar"><div style="width:${completed/scenes.length*100}%"></div></div></div><div class="hero-art"><img src="art/david-thumb.jpg" width="1200" height="1200" alt="David and Goliath illustrated coloring page"><div class="art-caption"><span>DAVID AND GOLIATH · 1 SAMUEL 17</span><span class="dots">${palette.slice(0,5).map(c=>`<i style="background:${c}"></i>`).join('')}</span></div></div></section>`:'';
 $('#app').innerHTML=`${hero}<div class="section-head"><div><span class="eyebrow">${view==='artwork'?'SAVED ON THIS DEVICE':'THE COLORING COLLECTION'}</span><h2>${titles[view]}</h2><p>${view==='journey'?'Follow the story in order, or choose any scene below.':view==='free'?'Choose any scene and any color. There are no wrong answers.':view==='artwork'?'Pick a picture to continue. Different detail levels save separately.':'Three new showcase stories · five distinct illustrations each · nine classic scenes preserved'}</p></div><span class="small">${list.length} scenes</span></div><section class="grid">${list.map(s=>{let p=progress(s);let stored=Object.entries(saved.works).filter(([k,w])=>k.startsWith(s.id+':')&&Object.keys(w.fills).length>0).sort((a,b)=>b[1].updated-a[1].updated)[0];const d=stored?.[0].split(':')[1]||(s.showcase?'v2-medium':'easy');return `<button class="card" data-open="${s.id}" aria-label="Color ${s.title}"><span class="picture">${s.showcase?`<img src="art/${s.id}-thumb.jpg" alt="${s.title} original V2 illustration" width="1200" height="1200" loading="lazy">`:decorative(illustration(s,d,stored?.[1].fills||{},!stored,false).svg)}</span><span class="order">${String(scenes.indexOf(s)+1).padStart(2,'0')} ${s.showcase?'V2 · ':''}${saved.finished.includes(s.id)?'✓':''}</span><span class="text"><span class="ref">${s.book}</span><span class="title">${s.title}</span><span class="status"><span>${p?p===100?'Completed':p+'% colored':stored?'In progress':'Choose your colors'}</span><span>↗</span></span></span></button>`;}).join('')}</section>${!list.length?'<div class="empty"><h2>Your first masterpiece is waiting.</h2><p>Color any scene and it will appear here automatically.</p><button class="primary" data-tab="journey">Start coloring →</button></div>':''}`;
 window.scrollTo(0,0);
}
async function openScene(id,restore=false){artReady=false;fills={};regions=[];history=[];future=[];current=scenes.find(s=>s.id===id);if(!current)return;if(!restore)difficulty=current.showcase?'v2-beginner':'easy';if(view==='free')mode='free';else if(!restore)mode='guided';if(view==='artwork'&&!restore){const last=Object.entries(saved.works).filter(([k,w])=>k.startsWith(id+':')&&Object.keys(w.fills).length>0).sort((a,b)=>b[1].updated-a[1].updated)[0];if(last){[,difficulty,mode]=last[0].split(':');}}const token=++loadingToken;try{if(difficulty.startsWith('v2-')){message('Opening your illustration…');await ensureArt(current,difficulty);if(token!==loadingToken)return;}}catch{if(token!==loadingToken)return;view='journey';renderGallery();message('Could not load artwork. Please reconnect and try again.');return;}history=[];future=[];fills={...(saved.works[key()]?.fills||{})};selected=0;custom=palette[0];completionShown=Object.keys(fills).length===illustration(current,difficulty).regions.length;pan=false;zoom=1;tx=0;ty=0;renderEditor();window.scrollTo(0,0);}
function renderEditor(){navigation();document.body.classList.add('coloring');const art=illustration(current,difficulty,fills,false,true);regions=art.regions;artReady=true;
 const choices=current.showcase?levels.map(l=>['v2-'+l,l[0].toUpperCase()+l.slice(1)]):[['easy','Classic Easy'],['detailed','Classic Detailed'],['expert','Classic Expert']];
 if(current.showcase&&Object.keys(saved.works).some(k=>k.startsWith(current.id+':')&&!k.split(':')[1].startsWith('v2-')))choices.push(['easy','Saved V1 Easy'],['detailed','Saved V1 Detailed'],['expert','Saved V1 Expert']);
 $('#app').innerHTML=`<section class="editor"><div class="editor-heading"><button data-action="back" aria-label="Return home">← Home</button><div><h1>${current.title}</h1><p>${current.book}</p></div><button data-action="story" aria-label="Read the story">Story</button></div><div class="editor-settings"><label>Detail <select id="difficulty">${choices.map(([id,name])=>`<option value="${id}" ${id===difficulty?'selected':''}>${name}</option>`).join('')}</select></label><label>Mode <select id="mode"><option value="guided" ${mode==='guided'?'selected':''}>By number</option><option value="free" ${mode==='free'?'selected':''}>Creative</option></select></label><label><input type="checkbox" id="numbers" ${numbers?'checked':''}> Numbers</label></div><div class="workspace"><div class="canvas-shell"><div class="viewport" id="viewport">${art.svg}</div><div class="canvas-tools"><button data-action="zoom-out" aria-label="Zoom out">−</button><button data-action="zoom-in" aria-label="Zoom in">+</button><button data-action="fit">Fit</button><button data-action="pan" aria-pressed="false" aria-label="Pan without coloring">✥ Pan</button><button data-action="hint">Find an area</button></div><span class="zoom-status" id="zoom-status"></span></div><aside class="palette-panel ${tray?'expanded':''}"><div class="tray-summary"><button data-action="tray" aria-expanded="${tray}" aria-controls="tray-content"><span id="selected-dot"></span><span id="selected-name"></span> <span>${tray?'⌄':'⌃'} Palette & tools</span></button><strong id="progress-text"></strong></div><div class="bar"><div id="progress-bar"></div></div><div id="tray-content" ${tray?'':'hidden'}><p id="color-caption"></p><div class="swatches">${palette.map((c,i)=>`<button class="swatch" style="background:${c}" data-color-choice="${i}" aria-label="Color ${i+1}: ${colorNames[i]}" aria-pressed="false">${i+1}</button>`).join('')}</div>${mode==='free'?`<label class="small">Custom color <input class="custom-color" id="custom" type="color" value="${custom}" aria-label="Custom color"></label><button data-action="eraser" aria-pressed="${eraser}">Eraser</button>`:''}<div class="panel-actions"><button data-action="undo" aria-label="Undo">↶ Undo</button><button data-action="redo" aria-label="Redo">↷ Redo</button><button data-action="download">Save artwork</button><button data-action="reset">Reset</button></div><p class="save-note">Saved on this device · <span id="remaining"></span></p></div></aside></div></section>`;
 setupPointers();update();requestAnimationFrame(()=>{if(current&&$('#viewport'))fit();});}
function storyCard(completed=false){const next=scenes[scenes.indexOf(current)+1];showModal(`<span class="eyebrow">${completed?'A BEAUTIFUL FINISH':'THE STORY BEHIND YOUR COLORS'}</span><h2>${current.title}</h2><b>${current.book}</b><p>${current.story}</p><h3>Think About It</h3><p>${current.think||'What does this story show you about God, and how can you respond today?'}</p><small>Original recap and reflection · Read the Bible reference for the full story.</small><div class="modal-buttons">${completed&&next?`<button class="primary" data-next="${next.id}">Next Story →</button>`:''}<button data-action="save-completed">Save Artwork</button>${completed?'<button data-action="color-again">Color Again</button>':''}<button data-action="close">${completed?'Keep enjoying my picture':'Back to coloring'}</button><button data-action="gallery">My Artwork / Progress</button></div>`);}
let hintCursor=0;let labelsFrame=0;function labelVisibility(){if(!labelsFrame)labelsFrame=requestAnimationFrame(()=>{labelsFrame=0;updateLabelVisibility();});}
function updateLabelVisibility(){
 if(!current)return;
 const v=$('#viewport'),svg=$('.color-art');if(!v||!svg)return;
 const size=v.clientWidth,units=difficulty.startsWith('v2-')?1200:600,scale=size/units*zoom;
 const view={x1:-tx/scale,y1:-ty/scale,x2:(v.clientWidth-tx)/scale,y2:(v.clientHeight-ty)/scale};
 const occupied=new Set(),nodes=[...svg.querySelectorAll('[data-label]')];
 nodes.sort((a,b)=>{
   const ar=regions[Number(a.dataset.label)],br=regions[Number(b.dataset.label)];
   const ap=ar?.color===selected&&!fills[ar.id]?1:0,bp=br?.color===selected&&!fills[br.id]?1:0;
   return bp-ap||Number(b.dataset.radius||50)-Number(a.dataset.radius||50);
 });
 for(const el of nodes){
   const r=regions[Number(el.dataset.label)],path=svg.querySelector(`[data-region="${el.dataset.label}"]`);if(!r||!path)continue;
   if(!el.dataset.homeX){el.dataset.homeX=el.getAttribute('x');el.dataset.homeY=el.getAttribute('y');}
   const box=path.getBBox(),ix1=Math.max(box.x,view.x1),iy1=Math.max(box.y,view.y1),ix2=Math.min(box.x+box.width,view.x2),iy2=Math.min(box.y+box.height,view.y2);
   const visibleW=Math.max(0,ix2-ix1),visibleH=Math.max(0,iy2-iy1),selectedMatch=mode==='guided'&&r.color===selected&&!fills[r.id];
   const minScreen=selectedMatch?6:(zoom<1.35?30:18);
   let lx=Number(el.dataset.homeX),ly=Number(el.dataset.homeY),found=false;
   if(visibleW*scale>=minScreen&&visibleH*scale>=minScreen){
     const cx=(ix1+ix2)/2,cy=(iy1+iy2)/2,candidates=[[cx,cy]];
     // Dense search for tiny/irregular visible pieces. The previous 9x9 search
     // could miss a perfectly playable sliver and leave it with no number.
     const steps=selectedMatch?16:8;
     for(let gy=0;gy<=steps;gy++)for(let gx=0;gx<=steps;gx++)candidates.push([ix1+(gx+.5)*visibleW/(steps+1),iy1+(gy+.5)*visibleH/(steps+1)]);
     for(const [px,py] of candidates){
       if(px<=ix1||px>=ix2||py<=iy1||py>=iy2)continue;
       try{if(path.isPointInFill(new DOMPoint(px,py))){lx=px;ly=py;found=true;break;}}catch{found=true;break;}
     }
   }
   // If the active region is visible but too skinny for an internal label,
   // keep it discoverable instead of silently creating an unnumbered hole.
   if(selectedMatch&&!found&&visibleW>0&&visibleH>0){
     const hx=Number(el.dataset.homeX),hy=Number(el.dataset.homeY);
     if(hx>=view.x1&&hx<=view.x2&&hy>=view.y1&&hy<=view.y2){lx=hx;ly=hy;found=true;}
   }
   const sx=lx*scale+tx,sy=ly*scale+ty;
   // Keep labels sparse at deep zoom. Tiny neighboring regions no longer create
   // a wall of repeated numbers over faces, armor and foliage.
   const spacing=selectedMatch?28:46,gx=Math.round(sx/spacing),gy=Math.round(sy/spacing);
   let crowded=false;for(let a=-1;a<=1;a++)for(let b=-1;b<=1;b++)if(occupied.has((gx+a)+':'+(gy+b)))crowded=true;
   const usefulRadius=selectedMatch?true:(Number(r.radius||0)*scale)>=10;
   // Only show the selected number in guided mode. This matches the way the
   // player is actually hunting areas and prevents unrelated numbers from
   // covering detailed faces/armor at high zoom.
   const relevant=mode!=='guided'||selectedMatch;
   const show=numbers&&relevant&&!fills[r.id]&&found&&usefulRadius&&sx>16&&sy>16&&sx<v.clientWidth-16&&sy<v.clientHeight-16&&!crowded;
   el.style.display=show?'':'none';
   if(show){
     occupied.add(gx+':'+gy);el.setAttribute('x',lx);el.setAttribute('y',ly);
     const screenFont=selectedMatch?19:16;
     el.setAttribute('font-size',String(screenFont/scale));el.setAttribute('font-weight',selectedMatch?'800':'700');
     el.setAttribute('stroke','#fffdf6');el.setAttribute('stroke-width',String(4/scale));el.setAttribute('paint-order','stroke');
   }
 }
}
function update(){if(!current||!artReady)return;const done=Object.keys(fills).length,pct=percent(fills,regions.length);$('#progress-text').textContent=`${pct}%`;$('#selected-name').textContent=(eraser&&mode==='free')?'Eraser':`${selected+1} · ${colorNames[selected]}`;$('#selected-dot').style.background=custom;$('#remaining').textContent=`${regions.length-done} areas remain`;const colorSet=regions.filter(r=>r.color===selected);$('#color-caption').textContent=`${colorSet.filter(r=>!fills[r.id]).length} of ${colorSet.length} areas remain for color ${selected+1}`;$('#progress-bar').style.width=pct+'%';
 $('.color-art').querySelectorAll('[data-region]').forEach(el=>{const id=Number(el.dataset.region);el.setAttribute('fill',fills[id]||'#fffdf6');el.classList.toggle('match',mode==='guided'&&!fills[id]&&Number(el.dataset.color)===selected);el.setAttribute('aria-label',`${regions[id].name}, color ${regions[id].color+1}${fills[id]?', colored':''}`);});
 labelVisibility();
 document.querySelectorAll('.swatch').forEach((el,i)=>{el.classList.toggle('chosen',i===selected);el.setAttribute('aria-pressed',String(i===selected));const set=regions.filter(r=>r.color===i);el.classList.toggle('done',mode==='guided'&&set.length>0&&set.every(r=>fills[r.id]));});
 $('[data-action="undo"]').disabled=!history.length;$('[data-action="redo"]').disabled=!future.length;
 if(done===regions.length&&!completionShown){completionShown=true;if(mode==='guided'&&!saved.finished.includes(current.id)){saved.finished.push(current.id);persist();}storyCard(true);}
}
function paint(id){if(!artReady)return;const r=regions[id];if(!r||pan)return;if(mode==='guided'&&r.color!==selected){message(`This area uses color ${r.color+1} · ${colorNames[r.color]}`);return;}const color=eraser&&mode==='free'?undefined:mode==='free'?custom:palette[selected];if(fills[id]===color)return;history.push({id,before:fills[id],after:color});future=[];if(color)fills[id]=color;else delete fills[id];saveWork();const set=regions.filter(x=>x.color===selected);update();const el=$(`[data-region="${id}"]`);el.classList.remove('filled-feedback');void el.getBoundingClientRect();el.classList.add('filled-feedback');if(mode==='guided'&&set.length&&set.every(x=>fills[x.id])&&!completionShown)message(`${colorNames[selected]} complete ✓`);}
function undo(redo=false){if(!artReady)return;const source=redo?future:history,dest=redo?history:future;const x=source.pop();if(!x)return;const value=redo?x.after:x.before;if(value)fills[x.id]=value;else delete fills[x.id];dest.push(x);saveWork();update();}
function transform(){const v=$('#viewport'),size=Math.min(v.clientWidth,v.clientHeight),artPx=size*zoom;const clamp=(t,edge)=>artPx<=edge?(edge-artPx)/2:Math.min(0,Math.max(edge-artPx,t));tx=clamp(tx,v.clientWidth);ty=clamp(ty,v.clientHeight);const svg=$('.color-art');const units=difficulty.startsWith('v2-')?1200:600;svg.style.width=size+'px';svg.style.height=size+'px';svg.style.left=((v.clientWidth-size)/2)+'px';svg.style.top=((v.clientHeight-size)/2)+'px';svg.style.transform='none';svg.style.transformOrigin='0 0';const vx=-tx*units/(size*zoom),vy=-ty*units/(size*zoom),vw=units/zoom;svg.setAttribute('viewBox',`${vx} ${vy} ${vw} ${vw}`);const b=$('[data-action="pan"]');b.classList.toggle('pan-on',pan);b.setAttribute('aria-pressed',String(pan));$('#zoom-status').textContent=`${Math.round(zoom*100)}% · ${pan?'Pan mode':'Tap to color · drag to move'}`;labelVisibility();}
function fit(){zoom=1;tx=ty=0;transform();}
function setZoom(z,cx,cy){const v=$('#viewport');cx=cx??v.clientWidth/2;cy=cy??v.clientHeight/2;const old=zoom;zoom=Math.max(1,Math.min(20,z));tx=cx-(cx-tx)*zoom/old;ty=cy-(cy-ty)*zoom/old;transform();}
function setupPointers(){const v=$('#viewport');let pointers=new Map(),start=null,moved=false,multi=false,pinch=null;
 v.addEventListener('pointerdown',e=>{e.preventDefault();try{v.setPointerCapture(e.pointerId);}catch{}pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===1){start={x:e.clientX,y:e.clientY,tx,ty,target:e.target.closest('[data-region]')};moved=false;multi=false;}else{multi=true;const [a,b]=[...pointers.values()];pinch={distance:Math.hypot(a.x-b.x,a.y-b.y),zoom,tx,ty,mx:(a.x+b.x)/2,my:(a.y+b.y)/2};}});
 v.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size>=2&&pinch){const [a,b]=[...pointers.values()],bounds=v.getBoundingClientRect(),mx=(a.x+b.x)/2-bounds.left,my=(a.y+b.y)/2-bounds.top,oldX=pinch.mx-bounds.left,oldY=pinch.my-bounds.top;zoom=Math.max(1,Math.min(20,pinch.zoom*Math.hypot(a.x-b.x,a.y-b.y)/Math.max(1,pinch.distance)));tx=mx-(oldX-pinch.tx)*zoom/pinch.zoom;ty=my-(oldY-pinch.ty)*zoom/pinch.zoom;transform();return;}if(start){const dx=e.clientX-start.x,dy=e.clientY-start.y;if(Math.hypot(dx,dy)>8)moved=true;if(moved&&(pan||zoom>1)){tx=start.tx+dx;ty=start.ty+dy;transform();}}});
 v.addEventListener('pointerup',e=>{pointers.delete(e.pointerId);if(!moved&&!multi&&start?.target)paint(Number(start.target.dataset.region));if(!pointers.size){start=null;pinch=null;}else{multi=true;}});
 v.addEventListener('pointercancel',e=>{pointers.delete(e.pointerId);start=null;multi=true;pinch=null;});
 v.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.dataset.region){e.preventDefault();paint(Number(e.target.dataset.region));}});
 v.addEventListener('wheel',e=>{e.preventDefault();const b=v.getBoundingClientRect();setZoom(zoom*(e.deltaY>0?.9:1.1),e.clientX-b.left,e.clientY-b.top);},{passive:false});
}
function hint(){
 const candidates=regions.filter(r=>!fills[r.id]&&(mode==='free'||r.color===selected)).sort((a,b)=>Number(b.radius||0)-Number(a.radius||0));
 if(!candidates.length){message('This color is complete. Choose another color.');return;}
 const r=candidates[hintCursor%candidates.length];hintCursor++;
 const el=$(`[data-region="${r.id}"]`),v=$('#viewport'),box=el.getBBox();
 const size=v.clientWidth,units=difficulty.startsWith('v2-')?1200:600;
 const targetScreen=Math.min(v.clientWidth,v.clientHeight)*.22;
 const fitZoom=targetScreen/Math.max(1,Math.min(Math.max(box.width,box.height),Math.sqrt(Math.max(1,box.width*box.height)))*size/units);
 zoom=Math.max(1.8,Math.min(4.25,fitZoom));
 tx=v.clientWidth/2-(box.x+box.width/2)*size/units*zoom;
 ty=v.clientHeight/2-(box.y+box.height/2)*size/units*zoom;
 transform();
 const label=$(`[data-label="${r.id}"]`);if(label){label.style.display='';label.setAttribute('font-weight','900');}
 el.classList.add('hint');el.focus({preventScroll:true});setTimeout(()=>el.classList.remove('hint'),2600);
 message(`Area found · color ${r.color+1} · tap Find again for the next one`);
}
async function download(){try{const art=illustration(current,difficulty,fills,false,false).svg;const blob=new Blob([art],{type:'image/svg+xml;charset=utf-8'}),url=URL.createObjectURL(blob),img=new Image();await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=reject;img.src=url;});const canvas=document.createElement('canvas');canvas.width=canvas.height=1800;canvas.getContext('2d').drawImage(img,0,0,1800,1800);URL.revokeObjectURL(url);const png=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));if(!png)throw Error();const downloadUrl=URL.createObjectURL(png);showModal(`<h2>Your artwork is ready.</h2><img src="${downloadUrl}" alt="Your colored ${current.title} picture" style="display:block;width:100%;border-radius:12px"><p>Download your picture, or touch and hold it to save on your phone.</p><div class="modal-buttons"><a class="primary export-link" href="${downloadUrl}" download="${current.id}-${difficulty}-light-and-life.png">Download PNG ↓</a><button data-action="close">Back to coloring</button></div>`);$('#modal').addEventListener('close',()=>URL.revokeObjectURL(downloadUrl),{once:true});}catch{message('Could not export this picture. Please try again.');}}
function action(a){if(a==='close'){closeModal();return;}if(a==='gallery'){closeModal();view='artwork';renderGallery();return;}if(!current)return;
 if(a==='story')storyCard(Object.keys(fills).length===regions.length);if(a==='tray'){tray=!tray;$('.palette-panel').classList.toggle('expanded',tray);$('#tray-content').hidden=!tray;const t=$('[data-action="tray"]');t.setAttribute('aria-expanded',String(tray));t.querySelector('span:last-child').textContent=(tray?'⌄':'⌃')+' Palette & tools';requestAnimationFrame(transform);}if(a==='eraser'){eraser=!eraser;const b=$('[data-action="eraser"]');if(b)b.setAttribute('aria-pressed',String(eraser));update();}if(a==='save-completed'){closeModal();download();}if(a==='color-again'){closeModal();action('reset');}
 if(a==='back'){saveWork();view='journey';renderGallery();return;}if(a==='undo')undo();if(a==='redo')undo(true);if(a==='zoom-in')setZoom(zoom*1.35);if(a==='zoom-out')setZoom(zoom/1.35);if(a==='fit')fit();if(a==='pan'){pan=!pan;transform();}if(a==='hint')hint();if(a==='download')download();if(a==='reset')showModal('<h2>A fresh page?</h2><p>This clears only this scene, detail level, and coloring mode. Your other pictures stay saved.</p><div class="modal-buttons"><button class="primary" data-action="confirm-reset">Start this picture over</button><button data-action="close">Keep my colors</button></div>');if(a==='confirm-reset'){fills={};history=[];future=[];completionShown=false;saveWork();closeModal();update();}}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.tab){if(current)saveWork();view=b.dataset.tab;mode=view==='free'?'free':'guided';renderGallery();}if(b.dataset.open)openScene(b.dataset.open);if(b.dataset.next){const id=b.dataset.next;closeModal();openScene(id);}if(b.dataset.action)action(b.dataset.action);if(b.dataset.colorChoice!==undefined){eraser=false;selected=Number(b.dataset.colorChoice);custom=palette[selected];if($('#custom'))$('#custom').value=custom;update();}});
document.addEventListener('change',e=>{if(e.target.id==='difficulty'||e.target.id==='mode'){saveWork();if(e.target.id==='difficulty')difficulty=e.target.value;else mode=e.target.value;openScene(current.id,true);}if(e.target.id==='numbers'){numbers=e.target.checked;update();}if(e.target.id==='custom'){custom=e.target.value;message('Custom color selected. Tap an area.');}});
$('.brand').onclick=e=>{e.preventDefault();if(current)saveWork();view='journey';renderGallery();};
$('#help').onclick=()=>showModal('<span class="eyebrow">A FEW SIMPLE STEPS</span><h2>Let’s add some color.</h2><p><b>1.</b> Choose a story and a detail level.<br><b>2.</b> Tap a color. In By number, tap areas with the same number.<br><b>3.</b> Pinch to zoom; drag to move when zoomed in. The Pan button also lets you move without coloring.<br><b>4.</b> Use Undo any time. Find an area shows one unfinished shape.<br><b>5.</b> Free color lets you pick any color, including your own.</p><p>Pictures save automatically in this browser. Use Save picture to keep a PNG. No account or payments required.</p><div class="modal-buttons"><button class="primary" data-action="close">I’m ready →</button></div>');
window.addEventListener('resize',()=>{if(current)fit();});window.addEventListener('pagehide',()=>{if(current)saveWork();});
const resume=saved.lastScene;renderGallery();if(resume&&scenes.some(s=>s.id===resume.id)){difficulty=resume.difficulty;mode=resume.mode;openScene(resume.id,true);}if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
