import {scenes,illustration,palette,colorNames} from './scenes.js?v=release1';
const $=s=>document.querySelector(s),KEY='ll-coloring-bible-release-v1';let saved={works:{},finished:[]};try{const x=JSON.parse(localStorage.getItem(KEY));if(x&&x.works&&Array.isArray(x.finished))saved=x;}catch{}
let view='journey',current=null,difficulty='easy',mode='guided',selected=0,custom=palette[0],numbers=true,regions=[],fills={},history=[],future=[],pan=false,zoom=1,tx=0,ty=0,toastTimer,completionShown=false;
const tabs=[['journey','Bible Journey'],['old','Old Testament'],['jesus','Life of Jesus'],['church','Early Church'],['free','Free Color'],['artwork','My Artwork / Progress']];
function message(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2700);}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(saved));return true;}catch{message('Storage unavailable. Download your picture before leaving.');return false;}}
function key(){return `${current.id}:${difficulty}:${mode}`;}
function saveWork(){saved.works[key()]={fills:{...fills},updated:Date.now()};persist();}
function percent(data,total){return Math.round(Object.keys(data).length/total*100)||0;}
function progress(scene){let best=0;for(const d of ['easy','detailed','expert'])for(const m of ['guided','free']){const w=saved.works[`${scene.id}:${d}:${m}`];if(w)best=Math.max(best,percent(w.fills,illustration(scene,d).regions.length));}return best;}
function showModal(html){const d=$('#modal');d.innerHTML=html;d.showModal();}
function closeModal(){$('#modal').close();}
function navigation(){ $('#navigation').innerHTML=tabs.map(([id,title])=>`<button data-tab="${id}" class="${view===id?'active':''}" aria-current="${view===id?'page':'false'}">${title}</button>`).join('');}
function nextScene(){return scenes.find(s=>!saved.finished.includes(s.id))||scenes[0];}
function decorative(svg){return svg.replace(/ role="button" tabindex="0"/g,'').replace('class="color-art"','class="color-art" aria-hidden="true"');}
function renderGallery(){current=null;document.body.classList.remove('coloring');navigation();const next=nextScene(),completed=saved.finished.length;let list=scenes;
 if(view==='old')list=scenes.filter(s=>s.group==='Old Testament');if(view==='jesus')list=scenes.filter(s=>s.group==='Life of Jesus');if(view==='church')list=scenes.filter(s=>s.group==='Early Church');if(view==='artwork')list=scenes.filter(s=>progress(s)>0);
 const titles={journey:'One story. So many colors.',old:'The Old Testament',jesus:'The life of Jesus',church:'Faith, shared with the world',free:'Your colors. Your imagination.',artwork:'Your little gallery'};
 const hero=view==='journey'?`<section class="hero"><div><span class="eyebrow">GENESIS TO REVELATION · VOLUME ONE</span><h1>A little color.<br>A beautiful story.</h1><p>Slow down, discover Scripture, and bring each page to life. A peaceful coloring journey for every age.</p><div class="hero-actions"><button class="primary" data-open="${next.id}">${completed?'Continue your journey':'Begin in Genesis'} →</button><button class="quiet" data-tab="free">Try free color</button></div><div class="journey-status">${completed} of ${scenes.length} stories completed</div><div class="bar"><div style="width:${completed/scenes.length*100}%"></div></div></div><div class="hero-art">${decorative(illustration(scenes[0],'detailed',{},true,false).svg)}<div class="art-caption"><span>CREATION · GENESIS 1</span><span class="dots">${palette.slice(0,5).map(c=>`<i style="background:${c}"></i>`).join('')}</span></div></div></section>`:'';
 $('#app').innerHTML=`${hero}<div class="section-head"><div><span class="eyebrow">${view==='artwork'?'SAVED ON THIS DEVICE':'THE COLORING COLLECTION'}</span><h2>${titles[view]}</h2><p>${view==='journey'?'Follow the story in order, or choose any scene below.':view==='free'?'Choose any scene and any color. There are no wrong answers.':view==='artwork'?'Pick a picture to continue. Different detail levels save separately.':'Original illustrations · three detail levels · no rush'}</p></div><span class="small">${list.length} scenes</span></div><section class="grid">${list.map(s=>{let p=progress(s);let stored=Object.entries(saved.works).filter(([k])=>k.startsWith(s.id+':')).sort((a,b)=>b[1].updated-a[1].updated)[0];const d=stored?.[0].split(':')[1]||'easy';return `<button class="card" data-open="${s.id}" aria-label="Color ${s.title}"><span class="picture">${decorative(illustration(s,d,stored?.[1].fills||{},!stored,false).svg)}</span><span class="order">${String(scenes.indexOf(s)+1).padStart(2,'0')} ${saved.finished.includes(s.id)?'✓':''}</span><span class="text"><span class="ref">${s.book}</span><span class="title">${s.title}</span><span class="status"><span>${p?p===100?'Completed':p+'% colored':'Choose your colors'}</span><span>↗</span></span></span></button>`;}).join('')}</section>${!list.length?'<div class="empty"><h2>Your first masterpiece is waiting.</h2><p>Color any scene and it will appear here automatically.</p><button class="primary" data-tab="journey">Start coloring →</button></div>':''}`;
 window.scrollTo(0,0);
}
function openScene(id,restore=false){current=scenes.find(s=>s.id===id);if(!current)return;if(view==='free')mode='free';else if(!restore)mode='guided';if(view==='artwork'&&!restore){const last=Object.entries(saved.works).filter(([k])=>k.startsWith(id+':')).sort((a,b)=>b[1].updated-a[1].updated)[0];if(last){[,difficulty,mode]=last[0].split(':');}}history=[];future=[];fills={...(saved.works[key()]?.fills||{})};selected=0;custom=palette[0];completionShown=Object.keys(fills).length===illustration(current,difficulty).regions.length;pan=false;zoom=1;tx=0;ty=0;renderEditor();window.scrollTo(0,0);}
function renderEditor(){navigation();document.body.classList.add('coloring');const art=illustration(current,difficulty,fills,false,numbers);regions=art.regions;
 $('#app').innerHTML=`<section class="editor"><div class="editor-heading"><div><h1>${current.title}</h1><p>${current.book} · ${scenes.indexOf(current)+1} / ${scenes.length}</p></div><button data-action="back">← Gallery</button></div><div class="editor-settings"><label>Detail <select id="difficulty"><option value="easy" ${difficulty==='easy'?'selected':''}>Easy</option><option value="detailed" ${difficulty==='detailed'?'selected':''}>Detailed</option><option value="expert" ${difficulty==='expert'?'selected':''}>Expert</option></select></label><label>Coloring <select id="mode"><option value="guided" ${mode==='guided'?'selected':''}>By number</option><option value="free" ${mode==='free'?'selected':''}>Free color</option></select></label><label><input type="checkbox" id="numbers" ${numbers?'checked':''}> Show numbers</label><span class="chip">${regions.length} areas</span></div><div class="workspace"><div class="canvas-shell"><div class="viewport" id="viewport">${art.svg}</div><div class="canvas-tools"><button data-action="undo" aria-label="Undo">↶ Undo</button><button data-action="redo" aria-label="Redo">↷ Redo</button><button data-action="zoom-out" aria-label="Zoom out">−</button><button data-action="zoom-in" aria-label="Zoom in">+</button><button data-action="fit">Fit</button><button data-action="pan" aria-pressed="false">✥ Pan</button></div><p class="mobile-tip">Tap to fill · pinch to zoom · drag to move when zoomed in</p></div><aside class="palette-panel"><h2>Pick a color</h2><p id="color-caption">${mode==='guided'?'Match the number on the picture.':'Use your imagination.'}</p><div class="swatches">${palette.map((c,i)=>`<button class="swatch" style="background:${c}" data-color-choice="${i}" aria-label="Color ${i+1}: ${colorNames[i]}" aria-pressed="false">${i+1}</button>`).join('')}</div>${mode==='free'?'<label class="small">Or make your own <input class="custom-color" id="custom" type="color" value="'+custom+'" aria-label="Custom color"></label>':''}<div class="progress-label"><strong id="progress-text"></strong><span id="save-label">Auto-saved</span></div><div class="bar"><div id="progress-bar"></div></div><div class="panel-actions"><button data-action="hint">⌕ Find an area</button><button data-action="download">↓ Save picture</button><button data-action="reset">Start over</button></div></aside></div><div class="story"><span class="eyebrow">THE STORY BEHIND YOUR COLORS</span><p>${current.story}</p><span class="small">Story summary · Read more in ${current.book}</span></div><p class="editor-note">${difficulty==='easy'?'Easy has large, friendly shapes.':difficulty==='detailed'?'Detailed adds smaller leaves, stones, and architectural details.':'Expert has many small details. Zoom in for the botanical borders and fine shapes.'} Progress is saved on this device.</p></section>`;
 setupPointers();update();}
function update(){if(!current)return;const done=Object.keys(fills).length,pct=percent(fills,regions.length);$('#progress-text').textContent=`${pct}% · ${done}/${regions.length}`;$('#progress-bar').style.width=pct+'%';$('#color-caption').textContent=mode==='guided'?`${selected+1} · ${colorNames[selected]} — tap matching areas`:'Every color is welcome.';
 $('.color-art').querySelectorAll('[data-region]').forEach(el=>{const id=Number(el.dataset.region);el.setAttribute('fill',fills[id]||'#fffdf6');el.classList.toggle('match',mode==='guided'&&!fills[id]&&Number(el.dataset.color)===selected);el.setAttribute('aria-label',`${regions[id].name}, color ${regions[id].color+1}${fills[id]?', colored':''}`);});
 $('.color-art').querySelectorAll('[data-label]').forEach(el=>el.style.display=numbers&&!fills[el.dataset.label]?'':'none');
 document.querySelectorAll('.swatch').forEach((el,i)=>{el.classList.toggle('chosen',i===selected);el.setAttribute('aria-pressed',String(i===selected));const set=regions.filter(r=>r.color===i);el.classList.toggle('done',mode==='guided'&&set.length>0&&set.every(r=>fills[r.id]));});
 $('[data-action="undo"]').disabled=!history.length;$('[data-action="redo"]').disabled=!future.length;
 if(done===regions.length&&!completionShown){completionShown=true;if(mode==='guided'&&!saved.finished.includes(current.id)){saved.finished.push(current.id);persist();}const next=scenes[scenes.indexOf(current)+1];showModal(`<div class="award">✦</div><span class="eyebrow">A BEAUTIFUL FINISH</span><h2>You brought the story to life.</h2><p>${current.story}</p><p>${mode==='guided'?'Your journey stamp has been saved.':'Your original colors have been saved in My Artwork.'}</p><div class="modal-buttons">${next?`<button class="primary" data-next="${next.id}">Next story →</button>`:'<button class="primary" data-action="gallery">See my artwork →</button>'}<button data-action="close">Keep enjoying my picture</button></div>`);}
}
function paint(id){const r=regions[id];if(!r||pan)return;if(mode==='guided'&&r.color!==selected){message(`Choose color ${r.color+1} · ${colorNames[r.color]}`);return;}const color=mode==='free'?custom:palette[selected];if(fills[id]===color)return;history.push({id,before:fills[id],after:color});future=[];fills[id]=color;saveWork();update();}
function undo(redo=false){const source=redo?future:history,dest=redo?history:future;const x=source.pop();if(!x)return;const value=redo?x.after:x.before;if(value)fills[x.id]=value;else delete fills[x.id];dest.push(x);saveWork();update();}
function transform(){const v=$('#viewport'),w=v.clientWidth;tx=Math.min(0,Math.max(w-w*zoom,tx));ty=Math.min(0,Math.max(w-w*zoom,ty));$('.color-art').style.transform=`translate(${tx}px,${ty}px) scale(${zoom})`; $('[data-action="pan"]').classList.toggle('pan-on',pan);$('[data-action="pan"]').setAttribute('aria-pressed',String(pan));}
function setZoom(z,cx,cy){const v=$('#viewport');cx=cx??v.clientWidth/2;cy=cy??v.clientHeight/2;const old=zoom;zoom=Math.max(1,Math.min(5,z));tx=cx-(cx-tx)*zoom/old;ty=cy-(cy-ty)*zoom/old;transform();}
function setupPointers(){const v=$('#viewport');let pointers=new Map(),start=null,moved=false,multi=false,pinch=null;
 v.addEventListener('pointerdown',e=>{e.preventDefault();v.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===1){start={x:e.clientX,y:e.clientY,tx,ty,target:e.target.closest('[data-region]')};moved=false;multi=false;}else{multi=true;const [a,b]=[...pointers.values()];pinch={distance:Math.hypot(a.x-b.x,a.y-b.y),zoom,tx,ty,mx:(a.x+b.x)/2,my:(a.y+b.y)/2};}});
 v.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size>=2&&pinch){const [a,b]=[...pointers.values()],bounds=v.getBoundingClientRect(),mx=(a.x+b.x)/2-bounds.left,my=(a.y+b.y)/2-bounds.top,oldX=pinch.mx-bounds.left,oldY=pinch.my-bounds.top;zoom=Math.max(1,Math.min(5,pinch.zoom*Math.hypot(a.x-b.x,a.y-b.y)/Math.max(1,pinch.distance)));tx=mx-(oldX-pinch.tx)*zoom/pinch.zoom;ty=my-(oldY-pinch.ty)*zoom/pinch.zoom;transform();return;}if(start){const dx=e.clientX-start.x,dy=e.clientY-start.y;if(Math.hypot(dx,dy)>8)moved=true;if(moved&&(pan||zoom>1)){tx=start.tx+dx;ty=start.ty+dy;transform();}}});
 v.addEventListener('pointerup',e=>{pointers.delete(e.pointerId);if(!moved&&!multi&&start?.target)paint(Number(start.target.dataset.region));if(!pointers.size){start=null;pinch=null;}else{multi=true;}});
 v.addEventListener('pointercancel',e=>{pointers.delete(e.pointerId);start=null;multi=true;pinch=null;});
 v.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.dataset.region){e.preventDefault();paint(Number(e.target.dataset.region));}});
 v.addEventListener('wheel',e=>{e.preventDefault();const b=v.getBoundingClientRect();setZoom(zoom*(e.deltaY>0?.9:1.1),e.clientX-b.left,e.clientY-b.top);},{passive:false});
}
function hint(){let r=regions.find(r=>!fills[r.id]&&(mode==='free'||r.color===selected));if(!r){r=regions.find(r=>!fills[r.id]);if(!r){message('Every area is colored!');return;}selected=r.color;custom=palette[selected];update();}const el=$(`[data-region="${r.id}"]`);zoom=1;tx=ty=0;transform();el.classList.add('hint');el.focus({preventScroll:true});setTimeout(()=>el.classList.remove('hint'),2500);message(`${r.name} · color ${r.color+1}`);}
async function download(){try{const art=illustration(current,difficulty,fills,false,false).svg;const blob=new Blob([art],{type:'image/svg+xml;charset=utf-8'}),url=URL.createObjectURL(blob),img=new Image();await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=reject;img.src=url;});const canvas=document.createElement('canvas');canvas.width=canvas.height=1800;canvas.getContext('2d').drawImage(img,0,0,1800,1800);URL.revokeObjectURL(url);const png=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));if(!png)throw Error();const downloadUrl=URL.createObjectURL(png);showModal(`<h2>Your artwork is ready.</h2><img src="${downloadUrl}" alt="Your colored ${current.title} picture" style="display:block;width:100%;border-radius:12px"><p>Download your picture, or touch and hold it to save on your phone.</p><div class="modal-buttons"><a class="primary export-link" href="${downloadUrl}" download="${current.id}-${difficulty}-light-and-life.png">Download PNG ↓</a><button data-action="close">Back to coloring</button></div>`);$('#modal').addEventListener('close',()=>URL.revokeObjectURL(downloadUrl),{once:true});}catch{message('Could not export this picture. Please try again.');}}
function action(a){if(a==='close'){closeModal();return;}if(a==='gallery'){closeModal();view='artwork';renderGallery();return;}if(!current)return;
 if(a==='back'){saveWork();renderGallery();}if(a==='undo')undo();if(a==='redo')undo(true);if(a==='zoom-in')setZoom(zoom*1.35);if(a==='zoom-out')setZoom(zoom/1.35);if(a==='fit'){zoom=1;tx=ty=0;transform();}if(a==='pan'){pan=!pan;transform();}if(a==='hint')hint();if(a==='download')download();if(a==='reset')showModal('<h2>A fresh page?</h2><p>This clears only this scene, detail level, and coloring mode. Your other pictures stay saved.</p><div class="modal-buttons"><button class="primary" data-action="confirm-reset">Start this picture over</button><button data-action="close">Keep my colors</button></div>');if(a==='confirm-reset'){fills={};history=[];future=[];completionShown=false;saveWork();closeModal();update();}}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.tab){if(current)saveWork();view=b.dataset.tab;mode=view==='free'?'free':'guided';renderGallery();}if(b.dataset.open)openScene(b.dataset.open);if(b.dataset.next){const id=b.dataset.next;closeModal();openScene(id);}if(b.dataset.action)action(b.dataset.action);if(b.dataset.colorChoice!==undefined){selected=Number(b.dataset.colorChoice);custom=palette[selected];if($('#custom'))$('#custom').value=custom;update();}});
document.addEventListener('change',e=>{if(e.target.id==='difficulty'||e.target.id==='mode'){saveWork();if(e.target.id==='difficulty')difficulty=e.target.value;else mode=e.target.value;openScene(current.id,true);}if(e.target.id==='numbers'){numbers=e.target.checked;update();}if(e.target.id==='custom'){custom=e.target.value;message('Custom color selected. Tap an area.');}});
$('#help').onclick=()=>showModal('<span class="eyebrow">A FEW SIMPLE STEPS</span><h2>Let’s add some color.</h2><p><b>1.</b> Choose a story and a detail level.<br><b>2.</b> Tap a color. In By number, tap areas with the same number.<br><b>3.</b> Pinch to zoom; drag to move when zoomed in. The Pan button also lets you move without coloring.<br><b>4.</b> Use Undo any time. Find an area shows one unfinished shape.<br><b>5.</b> Free color lets you pick any color, including your own.</p><p>Pictures save automatically in this browser. Use Save picture to keep a PNG. No account or payments required.</p><div class="modal-buttons"><button class="primary" data-action="close">I’m ready →</button></div>');
window.addEventListener('resize',()=>{if(current)transform();});window.addEventListener('pagehide',()=>{if(current)saveWork();});
renderGallery();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
