import {test} from 'node:test';
import assert from 'node:assert/strict';
import {scenes,illustration,palette} from './scenes.js';
test('The V1 journey spans Genesis through Revelation with unique stories',()=>{assert.equal(scenes[0].book,'Genesis 1');assert.match(scenes.at(-1).book,/Revelation/);assert.equal(new Set(scenes.map(s=>s.id)).size,scenes.length);});
for(const scene of scenes)test(`${scene.id}: every detail level has valid, stable, independently fillable regions`,()=>{let previous=0;for(const d of ['easy','detailed','expert']){const {regions,svg}=illustration(scene,d);assert.ok(regions.length>previous);previous=regions.length;assert.equal((svg.match(/data-region=/g)||[]).length,regions.length);const fills=Object.fromEntries(regions.map(r=>[r.id,palette[r.color]]));assert.ok(regions.every(r=>r.color>=0&&r.color<palette.length));assert.deepEqual(illustration(scene,d,fills).regions,regions);assert.equal(new Set(regions.map(r=>r.id)).size,regions.length);assert.ok(!illustration(scene,d,fills).svg.includes('fill="undefined"'));}});
import {readFileSync} from 'node:fs';
import {gunzipSync} from 'node:zlib';
import {createHash} from 'node:crypto';
for(const id of ['david','ark','storm'])test(`${id}: five distinct V2 illustration plates, region bounds and compressed integrity`,()=>{const hashes=[];const bounds=[[15,30],[30,70],[70,150],[150,300],[250,650]];for(const [i,level] of ['beginner','easy','medium','hard','expert'].entries()){const raw=readFileSync(`art/${id}-${level}.json`),art=JSON.parse(raw);assert.deepEqual(gunzipSync(readFileSync(`art/${id}-${level}.json.gz`)),raw);assert.ok(art.regions.length>=bounds[i][0]&&art.regions.length<=bounds[i][1]);assert.equal(new Set(art.regions.map(r=>r.id)).size,art.regions.length);assert.ok(art.regions.every(r=>r.color>=0&&r.color<12&&r.x>0&&r.x<1200&&r.y>0&&r.y<1200&&r.radius>0&&r.d.startsWith('M')));assert.ok(art.inkPath.length>10000);hashes.push(createHash('sha256').update(art.inkPath).digest('hex'));}assert.equal(new Set(hashes).size,5);});
